"use client";
import Script from "next/script";
import { useProjectConfig } from "../lib/useProjectConfig";
import { useEffect, useState } from "react";

export default function ClientHomePage({
	initialHtml,
	runtimeConfig,
	importMap,
}) {
	const { config } = useProjectConfig();
	const [html, setHtml] = useState(initialHtml);

	useEffect(() => {
		if (config && typeof window !== "undefined") {
			console.log("[DEBUG] Syncing data from Supabase:", config);

			// Update runtime config dynamically
			window.__APP_CONFIG__ = {
				...window.__APP_CONFIG__,
				tokenAddress: config.contract_address,
				pairAddress: config.dexscreener_url || "",
			};

			// Dispatch event for data.js to pick up
			window.dispatchEvent(
				new CustomEvent("tokenAddressUpdated", {
					detail: { address: config.contract_address },
				}),
			);

			// Update Social Links in the legacy HTML DOM manually
			const updateLinks = () => {
				const twitterLinks = document.querySelectorAll(
					'a[href*="twitter.com"], .desktop-icon[onclick*="twitter.com"]',
				);
				twitterLinks.forEach((link) => {
					if (link.tagName === "A") {
						link.href = config.twitter_url;
					} else {
						link.setAttribute(
							"onclick",
							`window.open('${config.twitter_url}', '_blank')`,
						);
					}
				});

				const communityLinks = document.querySelectorAll(
					'a[href*="t.me"], .desktop-icon[onclick*="t.me"]',
				);
				communityLinks.forEach((link) => {
					const url = config.community_url || config.telegram_url;
					if (link.tagName === "A") {
						link.href = url;
					} else {
						link.setAttribute("onclick", `window.open('${url}', '_blank')`);
					}
				});

				// Buy goes to the Pons launchpad for this token, always.
				const buyIcon = document.getElementById("buy-icon");
				const buyUrl = `https://www.ponsfamily.com/launchpad/${config.contract_address}`;
				if (buyIcon) {
					buyIcon.style.display = "";
					buyIcon.setAttribute("onclick", `window.open('${buyUrl}', '_blank')`);
				}
				document
					.querySelectorAll('a[href*="ponsfamily.com"], a[onclick*="ponsfamily.com"]')
					.forEach((link) => {
						link.href = buyUrl;
					});

				// dexscreener_url is generated by the admin panel and already points at
				// whichever chart platform was picked, so it is used verbatim.
				const chartIcon = document.getElementById("chart-icon");
				if (chartIcon) {
					if (config.dexscreener_url) {
						chartIcon.style.display = "";
						chartIcon.setAttribute(
							"onclick",
							`window.open('${config.dexscreener_url}', '_blank')`,
						);
					} else {
						chartIcon.style.display = "none";
					}
				}
			};

			const updateTwitterEmbed = () => {
				const panelContent = document.querySelector(
					"#twitter-panel .xp-content",
				);

				if (config.twitter_url && panelContent) {
					// Extract handle from URL, fallback to default handle
					const handleMatch = config.twitter_url.match(
						/(?:twitter\.com|x\.com)\/([^\/?]+)/,
					);
					const handle = handleMatch ? handleMatch[1] : "doobie_bot";

					panelContent.innerHTML = `<a class="twitter-timeline" data-theme="light" data-tweet-limit="3" href="https://twitter.com/${handle}">Posts by @${handle}</a>`;

					// Better way to wait for twttr
					if (window.twttr && window.twttr.widgets) {
						window.twttr.widgets.load(panelContent);
					} else {
						// Inject the script if not present
						if (!document.getElementById("twitter-wjs")) {
							const script = document.createElement("script");
							script.id = "twitter-wjs";
							script.src = "https://platform.twitter.com/widgets.js";
							script.async = true;
							script.onload = () => {
								if (window.twttr && window.twttr.widgets) {
									window.twttr.widgets.load(panelContent);
								}
							};
							document.head.appendChild(script);
						}
					}
				}
			};

			// Run immediately and also after a short delay to ensure DOM is ready
			updateLinks();
			updateTwitterEmbed();
			setTimeout(() => {
				updateLinks();
				updateTwitterEmbed();
			}, 1000);
		}
	}, [config, html]);

	return (
		<>
			<main
				dangerouslySetInnerHTML={{ __html: html }}
				suppressHydrationWarning
			/>
			<Script
				id="legacy-runtime-config"
				strategy="beforeInteractive"
				dangerouslySetInnerHTML={{
					__html: `window.__APP_CONFIG__ = ${runtimeConfig};`,
				}}
			/>
			<Script
				id="legacy-importmap"
				type="importmap"
				strategy="beforeInteractive"
				dangerouslySetInnerHTML={{ __html: importMap }}
			/>
			<Script
				id="legacy-main"
				src="/js/main.js?v=20241225-01"
				type="module"
				strategy="afterInteractive"
			/>
			<Script
				id="twitter-widget"
				src="https://platform.twitter.com/widgets.js"
				strategy="lazyOnload"
				onLoad={() => {
					const panelContent = document.querySelector(
						"#twitter-panel .xp-content",
					);
					if (window.twttr && window.twttr.widgets && panelContent) {
						window.twttr.widgets.load(panelContent);
					}
				}}
			/>
		</>
	);
}
